# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default='/home/music', max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('artists', models.ManyToManyField(to='artist.Artist')),
                ('available_country', models.ManyToManyField(to='country.Country')),
            ],
        ),
    ]
