# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
    ]
