# Generated by Django 2.0.1 on 2018-01-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20171114_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='available_country',
            field=models.ManyToManyField(default=(), to='country.Country'),
        ),
    ]
