# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_auto_20171114_1223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
